language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev g++-4.8
  - sudo sed -i -e 's|friend class hash|friend struct hash|' /usr/include/c++/4.8/bits/stl_bvector.h
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - cmake -DCMAKE_CXX_FLAGS=-Werror .
  - make
notifications:
  email: false
